<?php

/**
 * @file
 * Contains module_with_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function module_with_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the module_with_entity module.
    case 'help.page.module_with_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Our first module with entity') . '</p>';
      return $output;

    default:
  }
}

// /**
//  * Implements hook_theme().
//  */
// function module_with_entity_theme() {
//   return [
//     'module_with_entity' => [
//       'render element' => 'children',
//     ],
//   ];
// }

/**
 * Implements hook_theme().
 */
function module_with_entity_theme() {
  $theme = [];
  $theme['module_with_entity'] =  [
    'render element' => 'children',
  ];
  $theme['product_entity'] = [
    'render element' => 'elements',
    'file' => 'product_entity.page.inc',
    'template' => 'product_entity',
  ];
  $theme['product_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'product_entity.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function module_with_entity_theme_suggestions_product_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#product_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'product_entity__' . $sanitized_view_mode;
  $suggestions[] = 'product_entity__' . $entity->bundle();
  $suggestions[] = 'product_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'product_entity__' . $entity->id();
  $suggestions[] = 'product_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
