<?php

//Executer à l'installation

use Drupal\Core\Database\Database;

define('CONTACT_TABLE', 'contact');
define('TODO_TABLE', 'todo');

function createToDoTable() {
    $spec = [
        'description' => 'Todo',
        'fields' => [
            'id' => [
                'type' => 'serial',
                'not null' => TRUE
            ],
            'title' => [
                'type' => 'varchar',
                'not null' => TRUE,
                'length' => '100',
                'default' => ''
            ],
            'email' => [
                'type' => 'varchar',
                'not null' => TRUE,
                'length' => '255',
                'default' => ''
            ],
            'content' => [
                'type' => 'text',
                'not null' => TRUE,
                
            ],
        ],
        'primary key' => ['id']
    ];

    $schema = Database::getConnection()->schema();
    $schema->createTable(TODO_TABLE, $spec);
}


function mymodule_install()
{
    //Définition d'un schéma à exploiter par l'api Schema de Drupal
    $spec = [
        'description' => 'contact',
        'fields' => [
            'id' => [
                'type' => 'serial',
                'not null' => TRUE
            ],
            'name' => [
                'type' => 'varchar',
                'not null' => TRUE,
                'length' => '100',
                'default' => ''
            ]
        ],
        'primary key' => ['id']
    ];

    $schema = Database::getConnection()->schema();
    $schema->createTable(CONTACT_TABLE, $spec);

    createToDoTable();
}

//Executer à la dsinstallation
function mymodule_uninstall()
{
    $schema = Database::getConnection()->schema();
    $schema->dropTable(CONTACT_TABLE);
    $schema->dropTable(TODO_TABLE);
}

function mymodule_theme()
{
    $theme['mymodule_theme_todo'] = [
        'variables' => ['todos'=>NULL, 'message' => NULL],
        'template' => 'mymodule-todos-page'
    ];
    return $theme;
}


// function mymodule_theme($existing, $type, $theme, $path) {
//     return [
//       'my_template' => [
//         'variables' => ['todos' => NULL, 'message'=> NULL],
//       ],
//     ];
//   }